name: Build

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  build:
    runs-on: macos-12
    
    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: "14.0"
      - uses: actions/checkout@v2
      - name: xcodebuild
        run: xcodebuild -scheme Stack -sdk iphoneos -destination 'generic/platform=iOS'
