name: Build

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  build:
    runs-on: macos-13

    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: "14.3"
      - uses: actions/checkout@v2
      - name: xcodebuild
        run: xcodebuild -scheme SwiftUIStack -sdk iphoneos -destination 'generic/platform=iOS'

  test:
    runs-on: macos-13

    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: "14.3"
      - uses: actions/checkout@v2

      - name: Test
        run: xcodebuild -scheme SwiftUIStackTests -resultBundlePath results/SwiftUIStackTests.xcresult test -destination 'platform=iOS Simulator,name=iPhone 14 Pro,OS=16.4' | xcpretty

      - uses: kishikawakatsumi/xcresulttool@v1
        with:
          path: |
            results/SwiftUIStackTests.xcresult
        if: success() || failure()
